### ISSUE TITLE
Utility of the variable `ur_rslt`

### ISSUE THREAD

**Issue by TanguyBarthelemy** [rjdverse/rjd3revisions#32]
What is the utility of the variable `ur_rslt` ?

https://github.com/rjdemetra/rjd3revisions/blob/19d1db03403f369948d62e01f12eaad33918cd92/R/revision_analysis.R#L319

It is assigned but never used.

**Comment by clemasso** [comment]
It was indeed an unused residue from a previous version of the code. Thank you for reporting it! I have fixed this in: b4519ad0b414ea7f142c75e50697a1d86651c4ee
