### ISSUE TITLE
Other output_format  for `get_format`

### ISSUE THREAD

**Issue by AQLT** [rjdverse/rjd3revisions#6]
Since the template is simple, it could be good to enable other output_format than only html.
Moreover, not at it is not recommended to write by default in users home filespace.

**Comment by TanguyBarthelemy** [comment]
hi Alain, 
Yes it would be interesting to be able to export the report in other formats (pdf for example). 

Also, the `path.out` argument currently allows you to choose the destination of the generated file. But what is your opinion when the user does not provide a path. 
Is it better to return an **error** or choose another path?
Here the default destination is **not home** but **the working directory** of the user's project.
https://github.com/rjdemetra/rjd3revisions/blob/86696a12dcb41afa617c6731f0fac5c47aee2c0d/R/report.R#L47

**Comment by AQLT** [comment]
Hi Tanguy,
On the `path.out` option it is not allowed by CRAN policies (also in examples/vignettes). For CRAN we must only write/save files if the user has specified a directory in the function themselves.
That's why the `RJDemetra::save_spec()` [uses by default the `tempdir()` function](https://jdemetra.github.io/rjdemetra/reference/save_spec.html#ref-usage), `RJDemetra::save_worskpace()` [example use a `tempdir()`](https://jdemetra.github.io/rjdemetra/reference/save_workspace.html#ref-examples) and `rjwsacruncher::create_param_file()` [doesn't have any default directory](https://aqlt.github.io/rjwsacruncher/reference/create_param_file.html)

**Comment by TanguyBarthelemy** [comment]
Ok so:
- either generate an error if the `path.out` argument is missing,
- or generate it in a tempdir

**Comment by TanguyBarthelemy** [comment]
We extended the output to `.pdf` and `.html`. Maybe to `.docx` files but there are some problem with the tables currently.

**Comment by TanguyBarthelemy** [comment]
I think this issue can be closed.
